### ISSUE TITLE
Return values in arduino functions

### ISSUE THREAD

**Issue by darbyhewitt** [ACUOpticsResearch/motorized-monochromator#3]
The functions need return types to allow for better control of program flow. This will specifically help prevent the Arduino from attempting to execute multiple functions simultaneously. 

Motor-moving functions will return (via the serial connection) the wavelength once the motor motion is done

Wavelength-writing will return the written wavelength

**Comment by jtb14b** [comment]
Added return statements for motor-moving functions, as well as updating a confusing function name.
