### ISSUE TITLE
Separate Serial comm from hardware manipulation in Arduino code

### ISSUE THREAD

**Issue by darbyhewitt** [ACUOpticsResearch/motorized-monochromator#5]
Currently, all of the functions in the Arduino sketch do a little of both. Instead, let's break out all of the Serial commands and parse out function args in loop() before calling the corresponding functions, which will now be passed their appropriate arguments when called instead of parsing their arguments from the Serial link.

**Comment by jtb14b** [comment]
Moved serial commands out of functions and into loop()
