### ISSUE TITLE
add return types to functions and return value assignment in loop() in monochromatorControl2.ino

### ISSUE THREAD

**Issue by darbyhewitt** [ACUOpticsResearch/motorized-monochromator#9]
In loop, where "setWavelengthToMemory", "getWavelengthFromMemory", etc. are called, we should assign the returned value to a variable. Also, we should make sure that these functions return values. This will prevent the user from issuing a new command to the monochromator before the previous command has completed its execution.

**Comment by jtb14b** [comment]
Assigned return values to all  functions.
